### ISSUE TITLE
Copy Playlist Info broken

### ISSUE THREAD

**Issue by podpah** [SyndiShanX/Spicetify-Extensions#1]
# Version
Spotify for Windows (32 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.36.11
(I've also tried Spotify latest 1.2.37.701 and the same)

# Problem
Trying to use Copy Playlist Info does not work. Clicking the button doesn't change clipboard contents. I've tried a few versions the extension was working on, so I'm assuming this is caused by API changes

**Comment by SyndiShanX** [comment]
Hopefully that fixes it, thanks for reporting

**Comment by SyndiShanX** [comment]
If it isn't fixed, drop a link to your Playlist so I can see the error

**Comment by podpah** [comment]
Doesn't work with any playlist for me - Here's two I've tried on though:
https://open.spotify.com/playlist/2FJa8o2FN5K3O08CK6I0Xe?si=937179837ade4ac8
https://open.spotify.com/playlist/37i9dQZF1DWSIvbYYt1Dvi?si=da84731a229e451b

**Comment by SyndiShanX** [comment]
Try uninstalling/reinstalling the extension, it works for me on both of those

**Comment by podpah** [comment]
I've tried that but didn't work. I checked DevTools and the error I'm getting is:
```
vendor~xpui.js:1 Uncaught (in promise) TypeError: e.charCodeAt is not a function
    at n.length (vendor~xpui.js:1:128376)
    at d.string (vendor~xpui.js:1:2099357)
    at Object.encode (vendor~xpui.js:1:6602055)
    at Hn.get (vendor~xpui.js:1:6604972)
    at Yo.getPlaylist (xpui.js:1:2019617)
    at Yo.getMetadata (xpui.js:1:2020310)
    at copyPlaylistInfo (copyPlaylistInfo.js?time=1715704280829:21:51)
    at onClick (spicetifyWrapper.js:1763:6)
    at onClick (spicetifyWrapper.js:1531:7)
    at xpui.js:1:108682
n.length @ vendor~xpui.js:1
d.string @ vendor~xpui.js:1
encode @ vendor~xpui.js:1
get @ vendor~xpui.js:1
getPlaylist @ xpui.js:1
getMetadata @ xpui.js:1
copyPlaylistInfo @ copyPlaylistInfo.js?time=1715704280829:21
onClick @ spicetifyWrapper.js:1763
onClick @ spicetifyWrapper.js:1531
(anonymous) @ xpui.js:1
Me @ vendor~xpui.js:1
He @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ui @ vendor~xpui.js:1
Vi @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
ul @ vendor~xpui.js:1
Pe @ vendor~xpui.js:1
Wi @ vendor~xpui.js:1
zt @ vendor~xpui.js:1
Yt @ vendor~xpui.js:1
await in Yt (async)
onClick @ spicetifyWrapper.js:1763
onClick @ spicetifyWrapper.js:1531
(anonymous) @ xpui.js:1
Me @ vendor~xpui.js:1
He @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
Ui @ vendor~xpui.js:1
Vi @ vendor~xpui.js:1
(anonymous) @ vendor~xpui.js:1
ul @ vendor~xpui.js:1
Pe @ vendor~xpui.js:1
Wi @ vendor~xpui.js:1
zt @ vendor~xpui.js:1
Yt @ vendor~xpui.js:1
```

**Comment by SyndiShanX** [comment]
Hopefully it's fixed this time lol
